apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harness-secret-access
  namespace: harness-delegate-ng
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harness-secret-access-binding
  namespace: harness-delegate-ng
subjects:
  - kind: ServiceAccount
    name: helm-delegate
    namespace: harness-delegate-ng
roleRef:
  kind: Role
  name: harness-secret-access
  apiGroup: rbac.authorization.k8s.io


# please save this file locally and run the command locally on the master node 
# kubectl apply -f harness-secret-rbac.yaml
