pipeline:
  name: nexus-automation
  identifier: nexusautomation
  projectIdentifier: InfraAutomation
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Git Clone
        identifier: Git_Clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: harnessgitconnector
                    build:
                      type: branch
                      spec:
                        branch: master
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessgitconnector
        build: <+input>
