pipeline:
  name: Nexus Automation
  identifier: nexus_automation
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Clone Repository
        identifier: clone_repo
        type: CI
        spec:
          execution:
            steps:
              - step:
                  name: Clone Repo
                  identifier: clone_repo_step
                  type: GitClone
                  spec:
                    connectorRef: github_connector
                    repoName: rwirba/nexus-automation
                    branch: master
                    buildEnvironment:
                      mountPath: /harness/workspace
                      
    - stage:
        name: Check & Update Software
        identifier: check_update
        type: CI
        spec:
          infrastructure:
            type: Docker
            spec:
              connectorRef: docker_connector
              image: "nexus.kihhuf.org:8082/nexus-automation-runner:latest"
              shell: Bash
          execution:
            steps:
              - step:
                  name: Run Container & Execute Jobs
                  identifier: run_container
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Pulling Docker Image from Nexus..."
                      docker pull nexus.kihhuf.org:8082/nexus-automation-runner:latest

                      echo "Running the container and mounting workspace..."
                      docker run --rm -v /harness/workspace:/workspace nexus.kihhuf.org:8082/nexus-automation-runner:latest /bin/bash -c "
                        echo 'Checking for software updates...'
                        python3 /workspace/scripts/compare_versions.py

                        echo 'Downloading new versions...'
                        bash /workspace/scripts/download_binaries.sh

                        echo 'Uploading new versions to Nexus...'
                        python3 /workspace/scripts/upload_to_nexus.py

                        echo 'Update process completed!'
                      "

                      echo "Process complete. Container removed."
