pipeline:
  name: nexus-automation
  identifier: nexusautomation
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.gitconnector
        repoName: nexus-automation
        build: <+input>
  stages:
    - stage:
        name: gitclone
        identifier: gitclone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetes_connector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: nexus.kihhuf.org:8082/nexus-automation-runner:latest
                    shell: Sh
                    command: |-
                      echo "Checking for software updates..."
                      python3 /harness/workspace/scripts/compare_versions.py

                      echo "Downloading new versions..."
                      bash /harness/workspace/scripts/download_binaries.sh

                      echo "Uploading new versions to Nexus..."
                      python3 /harness/workspace/scripts/upload_to_nexus.py

                      echo "Update process completed!"
