- stage:
    name: Deploy Helm to Rancher
    identifier: deploy_helm
    type: Deployment
    spec:
      service:
        serviceDefinition:
          type: Kubernetes
          spec:
            manifests:
              - manifest:
                  identifier: helmChart
                  type: HelmChart
                  spec:
                    store:
                      type: Git
                      spec:
                        connectorRef: github_connector
                        repoName: rwirba/nexus-automation
                        branch: master
                        paths:
                          - helm/
      execution:  # <-- Move this inside spec
        steps:
          - step:
              name: Deploy Helm Chart
              identifier: deploy_helm_chart
              type: HelmDeploy
              spec:
                releaseName: nexus-automation
                namespace: nexus-automation
                chartPath: helm/
                valuesYaml: helm/values.yaml
