{{- if .Values.dockercfg }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.dockercfg }}
{{- end }}
