nexus:
  url: "http://nexus.kihhuf.org:8081/repository/infra"
  username: "admin"
  password: "admin123"

scripts:
  check_versions: "/app/scripts/compare_versions.py"
  download_binaries: "/app/scripts/download_binaries.sh"
  upload_nexus: "/app/scripts/upload_to_nexus.py"

jobs:
  image: "python:3.9"
  schedule: "0 2 * * *"  # Runs daily at 2 AM
